# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

    - name: Vendor
      run: go mod tidy; go mod vendor

    - name: Test
      run: GO111MODULE=on CGO_ENABLED=0 ginkgo -r -mod=vendor -cover --timeout 1m -output-dir=. -coverprofile=.coverage -gcflags "all=-l"  ./